Todolist App - DRF
artemjasan/daily_planner pull request #1
Opened 2021-02-21 13:03 UTC by artemjasan

- Updating project structure
- Adding DRF for creation API

2021-02-21 20:48 UTC, vrppaul commented
я пока не смотрел особо, но перестань называть папки проектов с большой буквы) так никто не делает

2021-02-28 20:44 UTC, vrppaul requested changes
руки дошли наконец-то

2021-02-28 20:44 UTC, vrppaul commented on backend/daily_planner/urls.py
> +]
у тебя в будущем наступит момент, когда тебе придется для каждого url писать префикс `api`. это можно упростить следующим способом
```
api_v1_patterns = [
    path('todo_list/', include('todolist_app.urls')),
    # остальные паттерны
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/, include(api_v1_patterns),
    # в будущем сможешь и вторую версию, если надо будет, вставить
]
```

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/models.py
> +        ordering = ('name',)
у тебя в будущем будут еще поля? если нет, то можно и оставить, но лишний код не есть хорошо в фазе, когда он не нужен

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/models.py
> +    completed = models.BooleanField(default=False, blank=True, null=True)
тут вопрос: как будет себя вести джанго, если пользователь ничего не укажет? у него же будет по дефолту `False`? зачем тогда бланк и нулл?

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/models.py
> +    category = models.ForeignKey(Category, default="General", on_delete=models.CASCADE)
хм, я не вижу в миграциях автоматическое заполнение данных для таблицы `Category`. что случится, если у тебя не будет в таблице `Category` значения `General`?

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/serializers.py
> +    category = TasksSeralizer(many=True, read_only=True)
а это точно `category`?

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/serializers.py
> +        fields = "__all__"
а вот вопрос. я тут поведение не помню, если указать `fields = "__all__"` и дополнтельные филды (у тебя `category`), то какие филды будут на выходе?

2021-02-28 20:44 UTC, vrppaul commented on backend/todolist_app/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
это зачем?

2021-02-28 20:44 UTC, vrppaul commented on backend/daily_planner/settings.py
> +)
это не проблема, но корс точно нужен, когда все на локалхосте? изучи эту тему, но здесь ничего менять не надо

2021-02-28 20:53 UTC, artemjasan commented on backend/todolist_app/models.py
> +    completed = models.BooleanField(default=False, blank=True, null=True)
Хмм, думаю тут лучше тогда оставить просто дефол = false, этого будет достаточно

2021-02-28 21:07 UTC, artemjasan commented on backend/daily_planner/settings.py
> +)
Я почитал, пишут что лучше добавлять

2021-02-28 21:09 UTC, vrppaul commented on backend/daily_planner/settings.py
> +)
Скинь почитать

2021-03-01 14:14 UTC, artemjasan commented on backend/todolist_app/models.py
> +        ordering = ('name',)
Я сейчас думаю над тем что не убрать ли мне полностью модель категории и вместо этого сделать констатну, которая будет являться словарем а там будут уже категории - и поле category в модели Task сделать как choice - сделать 10-15 базвых секций например.

```
DEF_CATGORY = "General"
CATEGORY  = {
"general" : "general"
"finance" : "finance"
etc
}

class Task(models.Model):
    category = models.CharField(choices=CATEGORY, default=DEF_CATGORY )
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False, blank=True, null=True)
```

2021-03-01 14:22 UTC, vrppaul commented on backend/todolist_app/models.py
> +        ordering = ('name',)
https://docs.djangoproject.com/en/3.1/ref/models/fields/#enumeration-types
советую тогда вот это

вот имплементация в срачате: https://github.com/srachat/srachat/blob/master/backend/srachat/models/comment.py#L15

2021-03-01 14:29 UTC, artemjasan commented on backend/todolist_app/serializers.py
> +        fields = "__all__"
все которые описаны в модели, даже дополнительные

2021-03-01 14:31 UTC, artemjasan commented on backend/todolist_app/serializers.py
> +    category = TasksSeralizer(many=True, read_only=True)
Я еще посмотрю - может и запутался, но вроде так должно быть

2021-03-01 14:33 UTC, vrppaul commented on backend/todolist_app/serializers.py
> +    category = TasksSeralizer(many=True, read_only=True)
Просто присваивать переменной category сериализатор тасков как-то странно

2021-03-01 14:34 UTC, vrppaul commented on backend/todolist_app/models.py
> +        ordering = ('name',)
Смотри мой комментарий ниже насчёт дефолта для foreign key

2021-03-01 14:42 UTC, artemjasan commented on backend/todolist_app/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
Когда читал туториал+ везде в других мануалах описывается что это удобно для отладки - работает примерно так же, хотя более приятная обработка ошибок, если мы посылаем неверные запросы.
https://www.django-rest-framework.org/tutorial/2-requests-and-responses/#adding-optional-format-suffixes-to-our-urls

2021-03-01 14:43 UTC, artemjasan commented on backend/todolist_app/models.py
> +    category = models.ForeignKey(Category, default="General", on_delete=models.CASCADE)
Мне кажется я понял в чем проблема - сейчас протестирую и испралю. Думаю сделать через константу DEFAULT_CAT = "General"

2021-03-01 14:44 UTC, artemjasan commented on backend/daily_planner/urls.py
> +]
Спасибо! не знал как это реализовать

2021-03-01 14:45 UTC, vrppaul commented on backend/todolist_app/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
ок, пусть останется. но если бы, например, это шло в продукцию, я бы советовал это убрать, так как тебе понадобится только json отображение, а эта строка немного вводит в ступор

2021-03-01 14:48 UTC, vrppaul commented on backend/todolist_app/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
в идеале ендпоинт должен возвращать только json, если ты в будущем будешь соединять к БЕ еще и ФЕ, например, на реакте

2021-03-01 18:56 UTC, artemjasan commented on backend/todolist_app/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
тогда я пока оставлю, но с пометкой что уже при соединение фе и бе надо убрать

2021-03-01 19:06 UTC, artemjasan commented on backend/todolist_app/models.py
> +    category = models.ForeignKey(Category, default="General", on_delete=models.CASCADE)
Я сейчас все протестирую и посмотрю как будет рабоать, но я только что понял что тот который был в ПР вариант со стринг указанием - не работает, он присваивал по алфавиту первое название категории

2021-03-01 20:44 UTC, artemjasan commented on backend/todolist_app/models.py
> +    category = models.ForeignKey(Category, default="General", on_delete=models.CASCADE)
До меня дошло что нужно бы сделать, но я не знаю как реализовать автозаполнение в дб этого значения))

2021-03-01 21:13 UTC, vrppaul commented on backend/todolist_app/models.py
> +    category = models.ForeignKey(Category, default="General", on_delete=models.CASCADE)
Тут есть несколько вариантов:
- оставить дефолт в foreign key
1) использовать id дефолтного значения
2) использовать to_field, указав, в каком именно поле должно искаться дефолтное значение. При этом этот филд должен иметь свойство unique
Но для этого тебе придётся заранее создать в таблице, на которую ссылается foreign key, это дефолтное значение. Это нужно сделать в новой мануально созданной миграции, чтобы ещё при создании всех таблиц во время миграции создавалось это необходимое значение. Или воспользоваться методом из этого ответа: https://stackoverflow.com/a/62697872
- заполнять этот филд в самом вью, где ты будешь проверять, указано ли значение для этого филда, и если нет,  то добавлять дефолт

2021-03-02 12:32 UTC, artemjasan commented on backend/daily_planner/urls.py
> +]
С этим у меня небольшие проблемы), хоть мы и указываем include('api_v1_patterns'), но он не хочет находить его и пишет no module....

2021-03-03 23:01 UTC, vrppaul requested changes
Всего две дробности осталось

2021-03-03 23:01 UTC, vrppaul commented on backend/todolist_app/models.py
> +    priority = models.CharField(max_length=10, choices=TaskPriority.choices, default=TaskPriority.LOW)
Это теперь будет PositiveSmallIntegerField

2021-03-03 23:01 UTC, vrppaul commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
Сейчас можно оставить и так,  но если в будущем будешь добавлять ещё чойс вью такие, то лучше объединить в один класс, что-то типа ChoiceListView, который будет настраивать класс аттрибут, например choices_class
Плюс здесь мне не нравится, что используются названия типов для создания словаря

2021-03-03 23:07 UTC, artemjasan commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
Согласен это тупо, но я просто долго думал как это обозвать и пока решил оставить так чтобы если даже забыл что писал - быстро вспомнить что куда.

2021-03-03 23:09 UTC, vrppaul commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
choice_id: choice_title?

2021-03-03 23:09 UTC, vrppaul commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
Если кто-то будет читать твой код, то этот человек никогда не поймёт,  что за инт и что за стринг)

2021-03-03 23:11 UTC, artemjasan commented on backend/todolist_app/models.py
> +    priority = models.CharField(max_length=10, choices=TaskPriority.choices, default=TaskPriority.LOW)
Меня смутило что во второй части мы имеем текст, но если я правильно понял он используется только для предоставления в фе или админ панели Джанго? А вся работа бе и хранение в БД  происходить в числовом варианте? Если это так то я понял почему смаллинтежер

2021-03-03 23:12 UTC, artemjasan commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
😐 действительно, логичные названия. Я переделаю завтра

2021-03-03 23:13 UTC, vrppaul commented on backend/todolist_app/models.py
> +    priority = models.CharField(max_length=10, choices=TaskPriority.choices, default=TaskPriority.LOW)
Филд модели имеет тип того,  что сохраняется
У чойсов сохраняется только первая часть,  вторая лишь для репрезентации

2021-03-03 23:13 UTC, artemjasan commented on backend/todolist_app/views.py
> +        return Response(priority_dict)
Да, думаю глупо выбрал, но я реально минут 15 пытался выдавить из себя хоть что-то адекватное😁

2021-03-03 23:14 UTC, artemjasan commented on backend/todolist_app/models.py
> +    priority = models.CharField(max_length=10, choices=TaskPriority.choices, default=TaskPriority.LOW)
Понял, переделаю. Я это искал кстати в мануалах, но там не упоминают об этом увы.

2021-03-03 23:27 UTC, vrppaul commented on backend/todolist_app/models.py
> +    priority = models.CharField(max_length=10, choices=TaskPriority.choices, default=TaskPriority.LOW)
Ну вот тут если посмотришь, то увидишь, что у инт чойсов инт поля в моделях: https://docs.djangoproject.com/en/3.1/ref/models/fields/#enumeration-types

2021-03-04 20:07 UTC, vrppaul approved these changes
Выглядит хорошо.  Написал один коммент, но он чисто для самолбразования

2021-03-04 20:07 UTC, vrppaul commented on backend/todolist_app/views.py
> +            choice_id: choice_title for choice_id, choice_title in Task.TaskCategories.choices
Я бы так и оставил, но попробуй, что будет если вместо этого написать просто `dict(Task.TaskCategories.choices)`

2021-03-04 21:33 UTC, artemjasan commented on backend/todolist_app/views.py
> +            choice_id: choice_title for choice_id, choice_title in Task.TaskCategories.choices
Работает

2021-03-04 21:35 UTC, vrppaul commented on backend/todolist_app/views.py
> +            choice_id: choice_title for choice_id, choice_title in Task.TaskCategories.choices
Так проще тогда будет, думаю. Чуть менее эксплицитно, но более питонистически

2021-03-04 21:44 UTC, artemjasan commented on backend/todolist_app/views.py
> +            choice_id: choice_title for choice_id, choice_title in Task.TaskCategories.choices
мне тоже нравится новый вариант

2021-03-04 21:44 UTC, merged

2021-03-04 21:44 UTC, vrppaul approved these changes