Weather app
artemjasan/daily_planner pull request #2
Opened 2021-03-09 12:21 UTC by artemjasan

The second mini app which can allows to type name of required city or cities and as a response user will receive general info about the weather in the selected city(s).

General info: 
- city name
- temperature
- description
- weather icon

Проблемы:
Когда открываю панель ДРФ, то там не отображаются поле name, которое указано в модели - из этого следует что я не могу зарегать новый город. Тоже самое касается когда обращаюсь к detailview - нет возможности изменить название 
города.
![Screenshot_2021-03-09 Weather List – Django REST framework](https://user-images.githubusercontent.com/58912225/110469288-c2d61280-80d9-11eb-99e6-e58c710f3491.png)
![Screenshot_2021-03-09 Weather Detail – Django REST framework](https://user-images.githubusercontent.com/58912225/110469365-d84b3c80-80d9-11eb-9a8f-f6e255eb67b1.png)

Однако если использовать Postman и в ключах явно указывать поле name и в качестве значения указывать город - то проблем нет, новый город регистрируется  и также  есть возможность изменить город 
![Screenshot from 2021-03-09 12-59-16](https://user-images.githubusercontent.com/58912225/110469539-0df02580-80da-11eb-88d5-72471ca25870.png)
![Screenshot from 2021-03-09 13-02-19](https://user-images.githubusercontent.com/58912225/110469571-18122400-80da-11eb-8017-4a3f926b65de.png)

2021-03-09 13:07 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
опиши мне, как ты видишь, что здесь происходит

2021-03-09 22:33 UTC, artemjasan commented on backend/weather_app/views.py
> +        return Response(weather_data)
Для мы получаем все объекты класса city из БД, и сохраняем в переменную cities.

Далее прогоняем полученный список через соответствующий сериализатор и переводим в json формат.

Создаём пустой лист weather_data. Через цикл for, проходим по всем уже существующим в БД городам. В переменную req записываем ответ в json формате от OpenApi, который мы формируем выше выше  + подставляем название города. 
Формируем словарь с заданными ключами и величинами - для первых двух ключей данные взяты из БД (id, name), остальные величины парсим из респонса OpenApi. 

После каждого прохода цикла for, добавляем соответствующий словарь в лист eeather_data. И в конце концов полученный список словарей (формат json) посылаем на наш ендпоинт

2021-03-09 22:36 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
1) не вижу использование сериализатора
2) если ты работаешь с моделью, то почему это просто APIView?
3) openapi - это документация, здесь ее нет, путаешь понятия

2021-03-09 22:42 UTC, artemjasan commented on backend/weather_app/views.py
> +        return Response(weather_data)
Насчёт 3 уже тоже посмотрел, перепутал названия. Я имел ввиду обращение к экстерниму ендпоинту.

2) использовал чистый APIView, потому что когда мы с тобой последний раз разговаривали ты сказал что для этого случая с экстерним эндпринтом (это же он?) лучше использовать его, но возможно я перепутал.

1) немного не понял что ты имеешь ввиду, то что фактически я его в респонсе не включаю?

2021-03-09 22:44 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
Ну ты создаешь объект serializator, но нигде его не используешь
Ты путаешь, apiview нужен тогда, когда ты не работаешь с моделью, здесь же удобнее будет использовать какой-нибудь ListCreate

2021-03-09 22:46 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
Ускорим процесс нахождения ошибки: ты все ещё не увидишь, почему у тебя нет поля name?

2021-03-09 22:49 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
Я тебе говорил о другом способе получения погоды:
У тебя будет один вью list create, который будет служить только для того, чтобы добавлять и получать города
Второй у тебя может быть lllist detail (просто сам сделаешь нужные миксины) view, который будет тоже работать с моделью городов, но будет чисто выдавать для них погоду

2021-03-09 22:49 UTC, artemjasan commented on backend/weather_app/views.py
> +        return Response(weather_data)
Да, у меня тоже были вопросы на этот счёт, в дитейл я из закоментил чтобы потом спросить. У меня на самом деле в этом месте ступор, то есть у меня сериализатор работает только с 2 полями модели это id и name, но кроме этого у меня получается ещё навиц данные которые я парсю с ответа. Именно над этим я долго парился и не мог понять как все это совместить

2021-03-09 22:54 UTC, artemjasan commented on backend/weather_app/views.py
> +        return Response(weather_data)
Ага, теперь понял что ты имел ввиду. Тогда у меня встречный вопрос, с первым вью все понятно я переделаю. А вот насчёт второго - там получается уже не нужны сериализатор, так как он будет чисто брать данные из БД и для них формировать данные с погодой? Я правильно себе представляю.

2021-03-10 10:34 UTC, vrppaul commented on backend/weather_app/views.py
> +        return Response(weather_data)
> Ага, теперь понял что ты имел ввиду. Тогда у меня встречный вопрос, с первым вью все понятно я переделаю. А вот насчёт второго - как мне реализовать это, мне нужен сериализатор? Наверное да, так как мне нужно удалять или изменять например название. Я вот этот момент не понимаю малость. До этого все было просто мы работали с полями и данными, которые описывались в модели. А тут получается в у модели города 2 поля, но по факту нам надо ещё подтянуть

начни с простого, создай вью для добавления и получения городов

2021-03-10 16:06 UTC, vrppaul reviewed
ок, теперь можем делать вью с погодой

2021-03-13 01:06 UTC, vrppaul requested changes
Есть, что исправлять пока

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/tests.py
> +# Create your tests here.
Напиши хотя бы пару тестов) или хотя бы issue создай

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +class ListCity(generics.ListCreateAPIView):
Новые города сможет добавлять кто угодно? Что будет, если человек добавит новый город, который не существует? Он будет отображаться в списке у всех?
Что если кто-то решит добавить сразу 100 городов?

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +            weather_data.append(city_weather)
Почему не list comprehension?

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +def call_api(city_name):
Максимально общее название. Из названия не понятно, что делает функция. Ты тайпинг не будешь использовать?

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +UNIT_SYSTEM = "units=metric"
Я бы все-таки units оставил в самом url, а вот metric оставил на настройку. Стоит вообще это делать отдельно?

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +API_ID = "appid=74fda670f4fb3091728731208163e6d8"
Это выглядит как sensitive data. Может, хотя бы в сеттинги добавить это? А лучше в env переменные, но для такого простого проекта необязательно

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +API_CALL = f"{URL_API}&{UNIT_SYSTEM}&{API_ID}"
Тогда уж API_CALL_URL

2021-03-13 01:06 UTC, vrppaul commented on backend/weather_app/views.py
> +    return err_msg
Получается, что у тебя при ошибке возвращаются другие данные? Я бы на твоём месте обдумал, как фе будет обрабатывать разные ответы
Зачем создаешь переменную зачем-то? Почему сразу не возвращать словарь

Что если возвращать словарь по типу
```
{
    "city": city_name,
    "data": data,
    "error": error_message
}
```
Где data может быть или словарь с данными, или None, чтобы потом на фе смотрели, если даты нет, то отобразить ошибку, которая будет передана в error, которая может быть None

2021-03-14 16:52 UTC, artemjasan commented on backend/weather_app/tests.py
> +# Create your tests here.
Сделаю иссью и буду писать все тесты когда сделаю для бэк для всех 4 мини приложений

2021-03-14 17:01 UTC, artemjasan commented on backend/weather_app/views.py
> +class ListCity(generics.ListCreateAPIView):
На данный момент нету пользователей, поэтому новые города добавляет кто хочет. Относительно кол-ва городов, думаю надо бы ограничить 3-5 городами, чтобы не было совсем каша

2021-03-14 17:02 UTC, vrppaul commented on backend/weather_app/views.py
> +class ListCity(generics.ListCreateAPIView):
Тогда issue на будущее

2021-03-14 17:04 UTC, artemjasan commented on backend/weather_app/views.py
> +class ListCity(generics.ListCreateAPIView):
Если город не существует то, на данный момент он выводит сообщение об ошибке. Я не знаю что с этим пока. Можно например придумать чтобы на основании кода статуса, он удалял город с неправильным названием (который не существует)

2021-03-14 17:05 UTC, artemjasan commented on backend/weather_app/views.py
> +def call_api(city_name):
Хочу использовать, но надо ещё посмотреть как это работает. Название поменяю

2021-03-14 17:06 UTC, artemjasan commented on backend/weather_app/views.py
> +UNIT_SYSTEM = "units=metric"
Ты предлагаешь плотностью в одну переменную все сделать, я разделил это для наглядности что откуда и за что отвечает

2021-03-14 17:08 UTC, vrppaul commented on backend/weather_app/views.py
> +UNIT_SYSTEM = "units=metric"
Если разделение ради наглядности, то это overengineering. Это лишнее

2021-03-14 17:08 UTC, artemjasan commented on backend/weather_app/views.py
> +API_ID = "appid=74fda670f4fb3091728731208163e6d8"
Да, мне уже гитхаб весточку прислал об этом. Там самое важное это айди, который уникален, остальное все в общем доступе. Вот его можно было бы перекинуть в енв, надо посмотреть как

2021-03-14 17:09 UTC, artemjasan commented on backend/weather_app/views.py
> +    return err_msg
Отличная идея, я до этого не додумался. Сделаю как ты предлагаешь.

2021-03-17 12:18 UTC, artemjasan commented on backend/weather_app/views.py
> +UNIT_SYSTEM = "units=metric"
понял

2021-05-01 08:55 UTC, merged